### ISSUE TITLE
下载证书失败: javax.crypto.AEADBadTagException: Tag mismatch!

### ISSUE THREAD

**Issue by hsldymq** [EliasZzz/CertificateDownloader#20]
JRE版本: 1.8
CertificateDownloader版本: v1.2.0

以下是工具执行的输出内容和报错信息:

body:{"data":[{"effective_time":"2023-10-20T17:13:42+08:00","encrypt_certificate":{"algorithm":"AEAD_AES_256_GCM","associated_data":"certificate","ciphertext":"GlhS6KpGjloLvDcwsfx1IgI9DRJIoFobYcSqlwc2g8bVt9Y+8f9opazMTAntFkwPwsyRHo87LJJwNqaDjbroEwalqueYlljcDH2OIzQHrma/MUkeYidayLKdt5CNbiMWGThicEoHinO+yvXCf5Rp8YjeMlMl5xju1rX/nd87CZXBtYKBDZRGRe8G3oPwECa8KekO6IkFnPD88Yp3dWQhgiso2Yx/macRdNczUlJq8mL2iaM9j4R1vdBhBfRyUlOctGEgRtlJz/ZrZDszs6XvjzOb75LL71gS0/Z35w3kOOYGwGga/A713w1yIT5HHDpg9M4Ooyp3o12hL8R8n2P/7pUPWmUkzL0t2YKwH/Jqk25ZhedClinwutQjvCs5bIlJHZeWlzhsRXhBwzieFOaObmG0Dueo10dkaixpKmQjlJ4iEb77GXLyUSf0ClS3jW7kyH4bNPTJiosSs/NuyrV83BLg++qYD6CPnlgNzEYb1hdwO3HjUo4efvpZpZ/1knXK373ivoZSVyVx8CNcq1lqLXlRIVqn8wC2IYmD5gBIgWdyBsIhvBzMb95vsd6tl9+xnkBtAfUZlG9S0gqMblJ30z91jQ9mwJa93NXC53G1ZJ+e5EzonVktunYMYn/PPbRH8zFZSAFexlx7rTVqkpTxL6UkAVqL12pXbJ6vC1+wkc/j5KkuJ6jGmsEW8SpNS6Rq0kewhSMmVaeKPsqoYyxSUcw3L6y0cC+5aVNlci99MAKzq9RnWzlf6GG1yM8kdnG54LsgCeehZASGHXuMYur8kUC1NU5lP1e8ymUr4sGbqd5Q1Sz1752NxuYZnvNogVZwI6XzrhO4QkDnFVs3a7fgpXGNUrMyiTs/k1PUwbQIztDIRn+yv5lHVjxWrLFG66pJH5LtZtM1TPSQ+ANIyKKZhmgLJ3C687xRqf0FKNa04JPQtyL3OZ60AXZyYSQYoSrMhg15KcIXv17JZXVXC8fSL9GKZfvDq/I5tRVOxjgd6J+CYmU/KnlyiYvUN7JOdbXw/IVeSMZv1nVpBusLEh7TnfP+OobDetvlHIHxxGDKyddICHYRDs20Sc+c84tJ9H+5sfEiVx0Y73CgR7fmRdMQJIGqdypTvgKe71pd5melidT58hPq5PUqGZ9++o5r7KOSeqfaU7+kjwM9yPTeR15PAtpUYT7TkAolb7njG/ouIXyafopHgJ162QMVIcfQB6Kpb1h72+nYB3wIJIMHvVfy2U+bGjZ9/rK37bN0v3tdTC+CLsAiswmD7IzZMsdumz5/w/7vPz2PDavTi2lzQjeODpFLtPV3TxgdYhPm4grCTPx8Dk2dJ0wf+djYdsC/9Np7XhxjgdTAnGfJmEdJkCmSH4jCdyXtoMEZ2tXxdWXa9Yo/bIqidvGQLXDLMXJByxQ1B2LckajOQXPRnuQCPlwnXjC6J+DhfkI8q1D1VEOxabge5hckH3+WI0NXwaIZ1C/nAJXq6lTKv5HK9G+SLcrHqweMzMN//2GR3kAToCeigD9OXqO16U3uCMZJ35DXcvFka9X66nXhe8RtBNO8yJNOWEBh8GxPSHb+NoWmGeUh4UMZjU3jb2LWfTAiTnJysEybSOOh8TBZ/Fxl5VI3kuJARrh53eKoQbd7WZKT4SUkhJPDaEh1POmJr3O94zkL/+37cmaZcHySatxl2xF7jLYqLI0paYT8AdEAWyhIFyMaORZXJ3E3JkUOQqiHJ+i5cPhxZDCXCjzg+sjh1j/ShTNzxft4dlGd4BipwCmvZ8iP+ySfvgoZhsUhpZP4ZSNPrkh1yN0D0+OTciU+gRHpV9jbw+KfOjRBej7m9xmjSqBzjifbqIgqGu/IM+fRypSfaAwtooBi+Du44+GjMMa3AtKAxkfKPWhirleHxFA4o76MtQYMaRKXXbYKwMm0Du8YUXnjo9XhV47Kv38TK89zoaT68NCVjqLcBLUZ3Jkg8h4tWhGokgNPPa60mR0/aT3SUJR43Bd2","nonce":"f5fe2fed4894"},"expire_time":"2028-10-18T17:13:42+08:00","serial_no":"6E953A17FCE93F59EC10DB96DBE12CDAFDB166AD"}]}
javax.crypto.AEADBadTagException: Tag mismatch!
        at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:620)
        at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
        at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
        at javax.crypto.Cipher.doFinal(Cipher.java:2168)
        at com.wechat.pay.contrib.apache.httpclient.util.AesUtil.decryptToString(AesUtil.java:42)
        at com.elias.CertificateDownloader.decryptAndValidate(CertificateDownloader.java:116)
        at com.elias.CertificateDownloader.downloadCertificate(CertificateDownloader.java:101)
        at com.elias.CertificateDownloader.run(CertificateDownloader.java:65)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2559)
        at picocli.CommandLine.run(CommandLine.java:3017)
        at picocli.CommandLine.run(CommandLine.java:2954)
        at com.elias.CertificateDownloader.main(CertificateDownloader.java:153)

**Comment by hsldymq** [comment]
我自己的问题, apiv3 key没有传对
